### ISSUE TITLE
Remove button not working

### ISSUE THREAD

**Issue by Zharkan** [garciaalvaro/melonpan-block-post-list#9] opened 2022-05-03 08:06 UTC
First of all, this is a very nice plugin to chose post so thank you for that.

I have an issue with the remove button, it's not working at all. Can you help me fix it please ?

**Comment by garciaalvaro** [comment] 2022-05-10 18:26
Hi, thank you.
I am not able to reproduce the bug, could you please let me know:
- which version of WordPress are you using?
- are you using Gutenberg plugin, if so, which version?

**Comment by garciaalvaro** [comment] 2022-05-11 21:29
I see what you mean and can reproduce it. I'm going to take a closer look.

**Comment by Zharkan** [comment] 2022-05-12 21:33
I thin I solved it, I opened a PR, thank you so much for all the hard work. I cloned it and customized it for a client that wanted this + i18n integration for his CPTs. It's perfect.

#10

**Comment by garciaalvaro** [comment] 2022-05-13 07:57
Thank you for opening a PR. Sorry I am bit busy these days, as soon as I can I will confirm it. I will keep this issue open until then.

**Comment by garciaalvaro** [comment] 2022-05-17 19:56
The PR has been merged, thank you.

**Closed by garciaalvaro** 2022-05-17 19:57 UTC
